require 'active_support/core_ext/object/blank'

module Roomer
  # Roomer::Schema extends ActiveRecord::Schema
  # Roomer::Schema is currently only supported by the Postgres database adapter

  class Schema < ActiveRecord::Migration[7.1]
    extend Roomer::Helpers::PostgresHelper

    def self.migrations_path(scope=:tenanted)
      case scope
        when :shared
          return Roomer.shared_migrations_directory
        when :tenanted
          return Roomer.tenanted_migrations_directory
        else
          raise 'Invalid scope parameter'
      end
    end

    def self.dump(scope=:tenanted)
      unless Roomer.heroku_safe && ENV['HEROKU_UPID']
        case scope
          when :shared
            schema_name = Roomer.shared_schema_name.to_s
            filename = Roomer.shared_schema_filename
          when :tenanted
            tenant = Tenant.first
            return if tenant.blank?

            schema_name = Tenant.first.schema_name.to_s
            filename = Roomer.tenanted_schema_filename
        end
        FileUtils.mkdir_p(Roomer.schemas_directory) unless File.exist?(Roomer.schemas_directory)
        filepath = File.expand_path(File.join(Roomer.schemas_directory, filename))
        tmp_filepath = "#{filepath}.tmp"
        ActiveRecord::Base.connection.schema_search_path = schema_name
        tmp_file = File.new(tmp_filepath, "w")
        Roomer::SchemaDumper.dump(ActiveRecord::Base.connection, tmp_file)
        tmp_file.close
        verify_reloadable!(tmp_filepath)
        FileUtils.mv(tmp_filepath, filepath)
      end
    end

    # Confirms a freshly dumped schema file can actually be loaded back before
    # it's allowed to replace the checked-in schema file. A dump generated by a
    # different ActiveRecord version than the one that produced the previous
    # file can be syntactically unrecognizable to this environment's loader
    # (e.g. unsupported create_table options), which would otherwise silently
    # corrupt the checked-in file and any tenant loaded from it afterwards.
    def self.verify_reloadable!(filepath)
      verify_schema_name = "roomer_schema_verify_#{Process.pid}"
      connection = ActiveRecord::Base.connection
      original_search_path = connection.schema_search_path
      original_verbose = ActiveRecord::Migration.verbose
      begin
        connection.transaction do
          create_schema(verify_schema_name)
          # Deliberately isolated to just the scratch schema (no real shared
          # schema on the path): an unqualified DROP/exists-check inside a
          # :force => true create_table would otherwise resolve through the
          # search path to the *real* production table and try to drop it.
          connection.schema_search_path = verify_schema_name
          # This replays the entire dump against a throwaway schema purely as
          # an internal integrity check, so it shouldn't spam the terminal
          # with a second copy of every create_table/add_index the real
          # migration already logged.
          ActiveRecord::Migration.verbose = false
          ensure_schema_migrations
          Object.send(:load, filepath)
          raise ActiveRecord::Rollback
        end
      rescue StandardError, ScriptError => e
        FileUtils.rm_f(filepath)
        raise "Generated schema file did not reload cleanly (#{e.class}: #{e.message}). " \
              "This usually means the local ActiveRecord version doesn't match whatever " \
              "generated the checked-in schema file. Aborting without overwriting it."
      ensure
        connection.schema_search_path = original_search_path
        ActiveRecord::Migration.verbose = original_verbose
      end
    end

    def self.load(schema_name, scope=:tenanted)
      ensuring_schema_and_search_path(schema_name) do
        filename = begin
          if scope == :shared
            Roomer.shared_schema_filename
          elsif scope == :tenanted
            Roomer.tenanted_schema_filename
          end
        end
        filepath = File.expand_path(File.join(Roomer.schemas_directory, filename))
        return unless File.exist?(filepath)
        # Object.load(filepath)
        Object.send(:load, filepath)
      end
    end

    def self.define(info={}, &block)
      new.instance_eval(&block)
      unless info[:version].blank?
        ActiveRecord::Base.connection.assume_migrated_upto_version(info[:version])
      end
    end

    def self.current_schema
      ActiveRecord::Base.connection.schema_search_path.split(",")[0]
    end

    def self.current_tenant
      return nil if current_schema == Roomer.shared_schema_name.to_s
      # requires_new: true wraps this in a SAVEPOINT so a failed lookup (e.g.
      # the tenants table isn't reachable from the current search path) only
      # rolls back this query instead of poisoning the whole enclosing
      # transaction for every statement after it.
      Tenant.transaction(requires_new: true) { Tenant.find_by_schema_name(current_schema) }
    rescue ActiveRecord::StatementInvalid
      nil
    end

  end
end
